/* ============================================================
   STAR WARS: A GALAXY LIFE
   Content data: eras, species, jobs, names, and life events.
   Flavor text is original, inspired by the broad strokes of
   Star Wars canon/lore (StarWars.com Databank, Wookieepedia,
   TheForce.net) — no text is copied from those sites.
   ============================================================ */

const ERAS = [
  { id: 'old-republic', name: "The Old Republic", years: "~5,000–1,000 BBY",
    blurb: "An ancient age of Jedi and Sith, ancient Sith Empires, Mandalorian Crusaders, and a Republic already thousands of years old.",
    hasJedi: true, hasSith: true, hasEmpire: false, hasFirstOrder: false, dark: 'sith' },
  { id: 'fall-of-jedi', name: "Fall of the Jedi", years: "~1,000–19 BBY",
    blurb: "The twilight of the Jedi Order. The Clone Wars rage across the galaxy as the Republic crumbles toward Empire.",
    hasJedi: true, hasSith: true, hasEmpire: false, hasFirstOrder: false, dark: 'sith' },
  { id: 'reign-of-empire', name: "Reign of the Empire", years: "19 BBY – 4 ABY",
    blurb: "The Galactic Empire rules the stars with an iron fist. A fledgling Rebel Alliance dares to resist.",
    hasJedi: false, hasSith: false, hasEmpire: true, hasFirstOrder: false, dark: 'empire' },
  { id: 'new-republic-rise', name: "Rise of the New Republic", years: "4–5 ABY",
    blurb: "The Empire reels after the Battle of Endor as a New Republic struggles to be born from the ashes.",
    hasJedi: false, hasSith: false, hasEmpire: true, hasFirstOrder: false, dark: 'empire' },
  { id: 'new-republic', name: "The New Republic Era", years: "5–34 ABY",
    blurb: "A fragile golden age of peace and rebuilding, with a New Jedi Order slowly rising from the ashes of the old.",
    hasJedi: true, hasSith: false, hasEmpire: false, hasFirstOrder: false, dark: 'shadow' },
  { id: 'first-order-rise', name: "Rise of the First Order", years: "34 ABY onward",
    blurb: "The shadowy First Order emerges from the wreckage of the Empire to make war on a Resistance few believe is necessary.",
    hasJedi: true, hasSith: false, hasEmpire: false, hasFirstOrder: true, dark: 'ren' },
  { id: 'new-jedi-order', name: "The New Jedi Order Era", years: "35 ABY onward",
    blurb: "A new generation rebuilds the Jedi Order under a fragile peace, while old shadows stir once more.",
    hasJedi: true, hasSith: false, hasEmpire: false, hasFirstOrder: false, dark: 'shadow' },
];

/* Species: trait deltas are applied to a base of 50 (0-100 scale).
   forceBonus nudges the midichlorian roll. weight = relative rarity
   when picking a random species (higher = more common). */
const SPECIES = [
  { id: 'human', name: 'Human', weight: 30, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 0, cha: 0 },
    homeworlds: ['Coruscant', 'Corellia', 'Alderaan', 'Naboo', 'Tatooine', 'Chandrila', 'Corulag', 'Jakku', 'Ord Mantell', 'Bespin'],
    blurb: 'Found on nearly every world in the galaxy, adaptable and endlessly ambitious.' },
  { id: 'twilek', name: "Twi'lek", weight: 6, lifespan: [60, 80], nameStyle: 'twilek', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 5, cha: 10 },
    homeworlds: ['Ryloth'], blurb: 'Head-tailed natives of Ryloth, known for their charm and resilience.' },
  { id: 'wookiee', name: 'Wookiee', weight: 4, lifespan: [200, 400], nameStyle: 'wookiee', forceBonus: 0,
    traits: { str: 25, int: 0, agi: -5, cha: 0 },
    homeworlds: ['Kashyyyk'], blurb: 'Towering, fur-covered warriors from the forest world of Kashyyyk, fiercely loyal.' },
  { id: 'zabrak', name: 'Zabrak', weight: 5, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 5, int: 5, agi: 0, cha: 0 },
    homeworlds: ['Iridonia', 'Dathomir'], blurb: 'Horned, hardy people known for their discipline and warrior traditions.' },
  { id: 'rodian', name: 'Rodian', weight: 5, lifespan: [60, 75], nameStyle: 'rodian', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 10, cha: -5 },
    homeworlds: ['Rodia'], blurb: 'Green-skinned hunters from Rodia with a cultural love of the chase.' },
  { id: 'moncal', name: 'Mon Calamari', weight: 4, lifespan: [60, 80], nameStyle: 'moncal', forceBonus: 0,
    traits: { str: 0, int: 10, agi: 0, cha: 0 },
    homeworlds: ['Mon Cala'], blurb: 'Amphibious, salmon-hued shipwrights and strategists from an ocean world.' },
  { id: 'quarren', name: 'Quarren', weight: 3, lifespan: [60, 80], nameStyle: 'moncal', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 0, cha: -5 },
    homeworlds: ['Mon Cala'], blurb: 'Squid-faced denizens of Mon Cala\'s ocean depths.' },
  { id: 'togruta', name: 'Togruta', weight: 4, lifespan: [60, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 10, cha: 5 },
    homeworlds: ['Shili'], blurb: 'Montral-and-lekku-crowned natives of Shili with a gift for spatial awareness.' },
  { id: 'chiss', name: 'Chiss', weight: 3, lifespan: [70, 90], nameStyle: 'chiss', forceBonus: 0,
    traits: { str: 0, int: 15, agi: 0, cha: -5 },
    homeworlds: ['Csilla'], blurb: 'Blue-skinned, red-eyed tacticians from the Unknown Regions.' },
  { id: 'duros', name: 'Duros', weight: 4, lifespan: [80, 100], nameStyle: 'duros', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 5, cha: 0 },
    homeworlds: ['Duro'], blurb: 'Among the galaxy\'s first great spacefarers, gray-skinned and keen-eyed.' },
  { id: 'trandoshan', name: 'Trandoshan', weight: 4, lifespan: [60, 90], nameStyle: 'trandoshan', forceBonus: 0,
    traits: { str: 15, int: 0, agi: 0, cha: -10 },
    homeworlds: ['Trandosha'], blurb: 'Reptilian, regenerating hunters who worship the thrill of the hunt.' },
  { id: 'bothan', name: 'Bothan', weight: 4, lifespan: [60, 70], nameStyle: 'bothan', forceBonus: 0,
    traits: { str: 0, int: 10, agi: 0, cha: 5 },
    homeworlds: ['Bothawui'], blurb: 'Fur-covered information brokers with a talent for espionage.' },
  { id: 'ithorian', name: 'Ithorian', weight: 3, lifespan: [60, 80], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 0, cha: 10 },
    homeworlds: ['Ithor'], blurb: 'Gentle, hammerhead-shaped herd philosophers devoted to their garden world.' },
  { id: 'sullustan', name: 'Sullustan', weight: 4, lifespan: [60, 80], nameStyle: 'sullustan', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 10, cha: 0 },
    homeworlds: ['Sullust'], blurb: 'Big-eared, big-eyed natives of a volcanic world, prized as pilots.' },
  { id: 'nautolan', name: 'Nautolan', weight: 3, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 5, int: 0, agi: 10, cha: 0 },
    homeworlds: ['Glee Anselm'], blurb: 'Tendril-headed amphibians attuned to the currents of life around them.' },
  { id: 'keldor', name: 'Kel Dor', weight: 3, lifespan: [80, 100], nameStyle: 'keldor', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 5, cha: 0 },
    homeworlds: ['Dorin'], blurb: 'Orange-skinned natives of Dorin who breathe through a specialized mask off-world.' },
  { id: 'devaronian', name: 'Devaronian', weight: 3, lifespan: [60, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 5, int: 0, agi: 0, cha: 5 },
    homeworlds: ['Devaron'], blurb: 'Horned wanderers with a deep-seated cultural love of exploration.' },
  { id: 'gungan', name: 'Gungan', weight: 4, lifespan: [60, 80], nameStyle: 'gungan', forceBonus: 0,
    traits: { str: 0, int: -10, agi: 10, cha: 0 },
    homeworlds: ['Naboo'], blurb: 'Amphibious dwellers of Naboo\'s underwater cities, boisterous and brave.' },
  { id: 'ewok', name: 'Ewok', weight: 3, lifespan: [50, 70], nameStyle: 'ewok', forceBonus: 0,
    traits: { str: -15, int: 0, agi: 10, cha: 5 },
    homeworlds: ['Endor'], blurb: 'Small, furry forest-dwellers of Endor with fierce tribal spirit.' },
  { id: 'chadrafan', name: 'Chadra-Fan', weight: 2, lifespan: [50, 65], nameStyle: 'sullustan', forceBonus: 0,
    traits: { str: -5, int: 5, agi: 15, cha: 0 },
    homeworlds: ['Chad'], blurb: 'Small, bat-eared, endlessly curious tinkerers.' },
  { id: 'aqualish', name: 'Aqualish', weight: 3, lifespan: [60, 80], nameStyle: 'human', forceBonus: 0,
    traits: { str: 10, int: 0, agi: 0, cha: -5 },
    homeworlds: ['Ando'], blurb: 'Walrus-faced amphibians with a reputation for toughness.' },
  { id: 'weequay', name: 'Weequay', weight: 3, lifespan: [60, 80], nameStyle: 'weequay', forceBonus: 0,
    traits: { str: 10, int: 0, agi: 0, cha: -10 },
    homeworlds: ['Sriluur'], blurb: 'Leather-skinned desert dwellers, common muscle for hire across the Rim.' },
  { id: 'kaminoan', name: 'Kaminoan', weight: 2, lifespan: [80, 120], nameStyle: 'kaminoan', forceBonus: 0,
    traits: { str: -10, int: 15, agi: 5, cha: 0 },
    homeworlds: ['Kamino'], blurb: 'Tall, slender geneticists from a stormy ocean world.' },
  { id: 'cerean', name: 'Cerean', weight: 2, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 20, agi: 0, cha: 0 },
    homeworlds: ['Cerea'], blurb: 'Binary-brained thinkers with elongated crania and a knack for strategy.' },
  { id: 'nikto', name: 'Nikto', weight: 3, lifespan: [60, 90], nameStyle: 'trandoshan', forceBonus: 0,
    traits: { str: 5, int: 0, agi: 5, cha: -10 },
    homeworlds: ['Kintan'], blurb: 'Reptilian survivors of a harsh, sun-scorched world.' },
  { id: 'zeltron', name: 'Zeltron', weight: 2, lifespan: [70, 90], nameStyle: 'human', forceBonus: 800,
    traits: { str: 0, int: 0, agi: 0, cha: 20 },
    homeworlds: ['Zeltros'], blurb: 'Pink-skinned empaths from a pleasure world, naturally attuned to emotion.' },
  { id: 'pantoran', name: 'Pantoran', weight: 3, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 0, cha: 5 },
    homeworlds: ['Pantora'], blurb: 'Blue-skinned natives of a domed, cloud-shrouded city-world.' },
  { id: 'dathomiri', name: 'Dathomirian', weight: 2, lifespan: [70, 100], nameStyle: 'dathomiri', forceBonus: 3000,
    traits: { str: 0, int: 0, agi: 0, cha: 5 },
    homeworlds: ['Dathomir'], blurb: 'Clan-born survivors of a haunted world steeped in ancient magick.' },
  { id: 'gran', name: 'Gran', weight: 3, lifespan: [60, 70], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 5, agi: 0, cha: 5 },
    homeworlds: ['Kinyen'], blurb: 'Three-eyed, good-natured herd folk known for their optimism.' },
  { id: 'toydarian', name: 'Toydarian', weight: 2, lifespan: [60, 80], nameStyle: 'toydarian', forceBonus: 0,
    traits: { str: 0, int: 10, agi: 0, cha: -5 },
    homeworlds: ['Toydaria'], blurb: 'Blue, hover-winged traders whose minds resist outside influence.' },
  { id: 'hutt', name: 'Hutt', weight: 1, lifespan: [500, 1000], nameStyle: 'hutt', forceBonus: 0,
    traits: { str: 10, int: 15, agi: -25, cha: 0 },
    homeworlds: ['Nal Hutta'], blurb: 'Slow-moving, long-lived crime lords whose slug-like bodies belie sharp minds.' },
  { id: 'ortolan', name: 'Ortolan', weight: 2, lifespan: [60, 80], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 0, agi: -5, cha: 5 },
    homeworlds: ['Orto'], blurb: 'Small, floppy-eared beings with an ear for music.' },
  { id: 'talz', name: 'Talz', weight: 2, lifespan: [60, 90], nameStyle: 'trandoshan', forceBonus: 0,
    traits: { str: 10, int: 0, agi: 0, cha: -5 },
    homeworlds: ['Alzoc III'], blurb: 'Fur-covered, multi-eyed natives of an ice world.' },
  { id: 'geonosian', name: 'Geonosian', weight: 2, lifespan: [60, 100], nameStyle: 'trandoshan', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 10, cha: -10 },
    homeworlds: ['Geonosis'], blurb: 'Insectoid hive-dwellers, tireless builders of war machines.' },
  { id: 'klatooinian', name: 'Klatooinian', weight: 2, lifespan: [60, 80], nameStyle: 'weequay', forceBonus: 0,
    traits: { str: 10, int: -5, agi: 0, cha: 0 },
    homeworlds: ['Klatooine'], blurb: 'Loyal, tusked servants long bound by ancient debts to the Hutts.' },
  { id: 'ugnaught', name: 'Ugnaught', weight: 2, lifespan: [50, 70], nameStyle: 'ewok', forceBonus: 0,
    traits: { str: 5, int: 5, agi: 0, cha: 0 },
    homeworlds: ['Gentes', 'Bespin'], blurb: 'Small, pink, industrious laborers found wherever hard work is needed.' },
  { id: 'iktotchi', name: 'Iktotchi', weight: 2, lifespan: [70, 90], nameStyle: 'human', forceBonus: 1200,
    traits: { str: 0, int: 10, agi: 0, cha: 0 },
    homeworlds: ['Iktotch'], blurb: 'Horned natives of a stormy moon, said to sense fragments of the future.' },
  { id: 'miraluka', name: 'Miraluka', weight: 1, lifespan: [70, 90], nameStyle: 'human', forceBonus: 5000,
    traits: { str: 0, int: 0, agi: 0, cha: 0 },
    homeworlds: ['Alpheridia'], blurb: 'An eyeless people who perceive the galaxy entirely through the Force.' },
  { id: 'echani', name: 'Echani', weight: 1, lifespan: [70, 90], nameStyle: 'human', forceBonus: 2200,
    traits: { str: 5, int: 0, agi: 15, cha: 0 },
    homeworlds: ['Eshan'], blurb: 'Master duelists whose martial bloodlines run unusually close to the Force.' },
  { id: 'falleen', name: 'Falleen', weight: 2, lifespan: [70, 90], nameStyle: 'human', forceBonus: 0,
    traits: { str: 0, int: 0, agi: 0, cha: 15 },
    homeworlds: ['Falleen'], blurb: 'Scaled, pheromone-gifted natives of a jungle world, famed for their allure.' },
  { id: 'mirialan', name: 'Mirialan', weight: 3, lifespan: [70, 90], nameStyle: 'human', forceBonus: 300,
    traits: { str: 0, int: 5, agi: 5, cha: 0 },
    homeworlds: ['Mirial'], blurb: 'Tattoo-marked desert people who prize discipline and self-mastery.' },
  { id: 'yodaspecies', name: "Unknown Species (Yoda's Kind)", weight: 0.15, lifespan: [800, 900], nameStyle: 'yoda', forceBonus: 12000,
    traits: { str: 0, int: 15, agi: 5, cha: 0 },
    homeworlds: ['an unknown world deep in Wild Space'], blurb: 'A vanishingly rare, unnamed species of small, wizened beings who live for centuries and swim in the Force from birth.' },
];

const NAME_POOLS = {
  human: {
    male: ['Anakin','Owen','Beru','Cade','Dain','Ezra','Finn','Garen','Han','Ivo','Jace','Kael','Luke','Mace','Nolan','Obi','Poe','Quill','Rex','Talon','Wedge','Zev','Corin','Dex','Farr'],
    female: ['Leia','Padme','Shara','Mara','Sabine','Jyn','Rey','Bail','Nara','Vella','Iden','Zara','Talia','Wren','Elin','Kira','Sana','Bree','Tam','Yara','Mira','Cassia','Vira'],
    last: ['Skywalker','Organa','Kenobi','Antilles','Erso','Solo','Bridger','Dorn','Vek','Wexley','Tano','Rook','Cerin','Vantor','Ardis','Nix','Rell','Karr','Denar','Vosh','Thane','Idren'],
  },
  twilek: { male: ["A'Sharad","Hutu","Nabrun","Toko","Ryo","Vec","Dax"], female: ["Aayla","Numa","Oola","Xime","Vaner","Chi","Risha"], last: [] },
  wookiee: { male: ['Chakko','Grahrwwr','Kelrahwwr','Malloc','Salporin','Wullffwarro','Attichitcuk'], female: ['Mallatobuck','Lohwoana','Freyya','Krruwhitte','Wyahatte'], last: [] },
  rodian: { male: ['Greedo','Wolfe','Sozz','Dhas','Tulik'], female: ["Neela","Vhira","Sozz'a","Tulla"], last: [] },
  moncal: { male: ['Ackbar','Cilghal','Meeko','Terrio','Nossor'], female: ['Raddus','Trina','Ossa','Miel'], last: [] },
  chiss: { male: ['Thrawn','Vurawn','Chaf','Baars'], female: ['Sev\'rance','Csera','Ar\'alani','Ziara'], last: ['Mitth','Csapla','Irizi','Nuruodo'] },
  duros: { male: ['Cham','Nako','Rugor','Vandu'], female: ['Elass','Sila','Ryndel'], last: ['Nadd','Iiestu','Xai'] },
  trandoshan: { male: ['Bossk','Dengit','Chak','Krrsantan'], female: ['Sriya','Vekk','Thossa'], last: [] },
  bothan: { male: ['Borsk','Fey\'lya','Koth','Tav'], female: ['Chihi','Sesk','Wynna'], last: ['Var','Fel\'ya','Or\'lya'] },
  sullustan: { male: ['Nien','Rapoc','Sligh','Wompo'], female: ['Chalk','Mira','Sula'], last: ['Nunb','Pavo','Vozz'] },
  keldor: { male: ['Plo','Torv','Zeth'], female: ['Neela','Vha','Sora'], last: ['Koon','Torv'] },
  gungan: { male: ['Jar Jar','Boss','Roos','Rugor'], female: ['Peppi','Ruwee','Wanya'], last: ['Binks','Nass','Tarr'] },
  ewok: { male: ['Wicket','Teebo','Chirpa','Logray'], female: ['Kneesaa','Latara','Malani'], last: [] },
  weequay: { male: ['Hondo','Kithaba','Obara','Vashi'], female: ['Sela','Nira','Kova'], last: [] },
  kaminoan: { male: ['Lama','Taun','Nala'], female: ['Su','Reeva','Chala'], last: ['Su','Se'] },
  dathomiri: { male: ['Maul','Savage','Feral','Kadin'], female: ['Talzin','Merrin','Asajj','Karis'], last: [] },
  toydarian: { male: ['Watto','Groff','Bahn'], female: ['Sila','Reha'], last: [] },
  hutt: { male: ['Jabba','Ziro','Gorga','Popara','Bo'], female: ['Voxx','Grakka','Sillha'], last: [] },
  yoda: { male: ['Yaddle','Vandar','Oteg','Bregga'], female: ['Yaddle','Vinda','Oreg'], last: [] },
};

const SYLLABLES = ['ka','ren','tho','mek','va','lu','pri','on','za','ith','qui','del','sha','ros','nim','tor','ax','vel','uu','yin','po','rex','tik','mora'];

const JOBS = [
  { id: 'moisture-farmer', title: 'Moisture Farmer', pay: [500, 1500], minAge: 14, smarts: 0 },
  { id: 'mechanic', title: 'Droid & Starship Mechanic', pay: [800, 2200], minAge: 15, smarts: 20 },
  { id: 'pilot', title: 'Starship Pilot', pay: [1500, 4200], minAge: 16, smarts: 30 },
  { id: 'smuggler', title: 'Smuggler', pay: [1000, 6500], minAge: 16, smarts: 20, risky: true },
  { id: 'bounty-hunter', title: 'Bounty Hunter', pay: [1500, 7500], minAge: 18, smarts: 25, risky: true },
  { id: 'cantina-owner', title: 'Cantina Owner', pay: [1000, 3200], minAge: 20, smarts: 15 },
  { id: 'merchant', title: 'Merchant Trader', pay: [1000, 3500], minAge: 16, smarts: 15 },
  { id: 'senator', title: 'Galactic Senator', pay: [3000, 9000], minAge: 30, smarts: 55, eras: ['old-republic','fall-of-jedi','new-republic-rise','new-republic','new-jedi-order'] },
  { id: 'imperial-officer', title: 'Imperial Officer', pay: [2000, 5500], minAge: 18, smarts: 30, eras: ['reign-of-empire'] },
  { id: 'stormtrooper', title: 'Stormtrooper', pay: [1000, 2500], minAge: 18, smarts: 0, eras: ['reign-of-empire'], risky: true },
  { id: 'rebel-operative', title: 'Rebel Alliance Operative', pay: [500, 2200], minAge: 16, smarts: 20, eras: ['reign-of-empire'], risky: true },
  { id: 'resistance-fighter', title: 'Resistance Fighter', pay: [500, 2200], minAge: 16, smarts: 20, eras: ['first-order-rise'], risky: true },
  { id: 'first-order-officer', title: 'First Order Officer', pay: [2000, 5500], minAge: 18, smarts: 30, eras: ['first-order-rise'] },
  { id: 'clone-trooper', title: 'Clone Trooper', pay: [1000, 2500], minAge: 18, smarts: 0, eras: ['fall-of-jedi'], risky: true },
  { id: 'separatist-tech', title: 'Separatist Droid Technician', pay: [1000, 2600], minAge: 16, smarts: 25, eras: ['fall-of-jedi'] },
  { id: 'doctor', title: 'Medical Doctor', pay: [2500, 6500], minAge: 24, smarts: 60 },
  { id: 'scientist', title: 'Scientist / Engineer', pay: [3000, 7500], minAge: 22, smarts: 70 },
  { id: 'podracer', title: 'Podracer', pay: [500, 9500], minAge: 12, smarts: 10, eras: ['old-republic','fall-of-jedi'], risky: true },
  { id: 'gladiator', title: 'Arena Gladiator', pay: [500, 4500], minAge: 16, smarts: 0, risky: true },
  { id: 'pirate', title: 'Pirate', pay: [1000, 6000], minAge: 16, smarts: 10, risky: true },
  { id: 'hutt-enforcer', title: 'Hutt Cartel Enforcer', pay: [1500, 5500], minAge: 16, smarts: 10, risky: true },
  { id: 'spice-runner', title: 'Spice Runner', pay: [2000, 7500], minAge: 16, smarts: 15, risky: true },
  { id: 'journalist', title: 'Holonet Reporter', pay: [1000, 3200], minAge: 18, smarts: 35 },
  { id: 'musician', title: 'Cantina Musician', pay: [500, 2200], minAge: 14, smarts: 5 },
  { id: 'farmer', title: 'Farmer', pay: [400, 1200], minAge: 12, smarts: 0 },
  { id: 'miner', title: 'Miner', pay: [600, 1900], minAge: 15, smarts: 5 },
  { id: 'ship-captain', title: 'Freighter Captain', pay: [2000, 5500], minAge: 22, smarts: 25 },
  { id: 'explorer', title: 'Galactic Explorer', pay: [1000, 3200], minAge: 18, smarts: 30 },
  { id: 'slicer', title: 'Slicer (Hacker)', pay: [1500, 5500], minAge: 14, smarts: 45, risky: true },
  { id: 'teacher', title: 'Scholar / Teacher', pay: [1000, 3200], minAge: 22, smarts: 40 },
  { id: 'mandalorian', title: 'Mandalorian Warrior', pay: [1500, 5500], minAge: 16, smarts: 10, risky: true },
  { id: 'nightsister', title: 'Nightsister Acolyte', pay: [500, 2200], minAge: 14, smarts: 10, eras: ['old-republic','fall-of-jedi','reign-of-empire'] },
  { id: 'new-republic-officer', title: 'New Republic Fleet Officer', pay: [2000, 5500], minAge: 18, smarts: 30, eras: ['new-republic-rise','new-republic'] },
];

/* ---------------- EVENTS ---------------- */
/* Each flavor event: { text, stages:[...], effects:{...}, weight? } */
function E(text, stages, effects, extra) { return Object.assign({ text, stages, effects: effects || {} }, extra || {}); }

const FLAVOR_EVENTS = [
  // BABY
  E("You took your first steps, wobbling across the durasteel floor.", ['baby'], { happiness: 5 }),
  E("You babbled your first word — it might have been a curse in Huttese.", ['baby'], { happiness: 3 }),
  E("A family droid sang you to sleep with an old spacer's lullaby.", ['baby'], { happiness: 4 }),
  E("You caught a mild fever from the recycled ship air, but recovered.", ['baby'], { health: -5 }),
  E("Your parents argued over what to name you for the third time.", ['baby'], { happiness: -2 }),
  E("A meteor shower lit up the sky the night you were born — locals called it a good omen.", ['baby'], { happiness: 4 }),
  E("You grabbed a passing Jawa's finger and wouldn't let go.", ['baby'], { happiness: 2 }),
  E("You slept through an entire planetary thunderstorm.", ['baby'], { health: 2 }),
  // CHILD
  E("You built a wobbly tower out of old blaster casings.", ['child'], { smarts: 3, happiness: 3 }),
  E("You got lost in a crowded market for twenty terrifying minutes.", ['child'], { happiness: -4 }),
  E("A street performer taught you a simple sleight-of-hand trick.", ['child'], { smarts: 2, looks: 1 }),
  E("You fell out of a tree (or off a landing platform) and skinned your knee.", ['child'], { health: -3 }),
  E("You made a best friend at the local schoolyard.", ['child'], { happiness: 6 }),
  E("You asked entirely too many questions about hyperspace travel.", ['child'], { smarts: 4 }),
  E("You were scolded for poking around an old droid's internals.", ['child'], { smarts: 2, happiness: -1 }),
  E("You won a footrace against the older kids on your block.", ['child'], { happiness: 5, looks: 1 }),
  E("A traveling storyteller filled your head with tales of ancient wars.", ['child'], { smarts: 3, happiness: 3 }),
  E("You caught a nasty bug going around the crèche.", ['child'], { health: -6 }),
  // PRETEEN
  E("You started sneaking off to watch ships take off from the spaceport.", ['preteen'], { happiness: 4 }),
  E("You got into your first real schoolyard scuffle.", ['preteen'], { health: -3, happiness: -2 }),
  E("You aced a difficult exam on galactic history.", ['preteen'], { smarts: 6 }),
  E("You had an embarrassing growth spurt at the worst possible time.", ['preteen'], { looks: -2 }),
  E("You started tinkering with a busted speeder bike engine.", ['preteen'], { smarts: 4 }),
  E("A local bully mocked your accent (or your species). You stood your ground.", ['preteen'], { happiness: -3, health: -1 }),
  E("You discovered a talent for haggling in the market stalls.", ['preteen'], { smarts: 3, wealth: 40 }),
  E("You developed your first serious crush.", ['preteen'], { happiness: 5 }),
  // TEEN
  E("You threw a party while your parents were off-world. It got out of hand.", ['teen'], { happiness: 8, health: -3 }),
  E("You picked up a part-time gig running errands at the docking bay.", ['teen'], { wealth: 150 }),
  E("You aced your pilot's aptitude test at school.", ['teen'], { smarts: 6, happiness: 2 }),
  E("You got a questionable tattoo you're not totally sure about.", ['teen'], { looks: 2, happiness: 1 }),
  E("You spent a whole season obsessed with a holodrama about a rogue smuggler.", ['teen'], { happiness: 3 }),
  E("You were caught sneaking into an off-limits cantina.", ['teen'], { happiness: 4, health: -2 }),
  E("You worked out constantly and started filling out your frame.", ['teen'], { looks: 4, health: 3 }),
  E("Your first real heartbreak hit hard.", ['teen'], { happiness: -8 }),
  E("You joined a local sports league and made the starting roster.", ['teen'], { health: 5, happiness: 4 }),
  // ADULT
  E("You upgraded your living quarters with hard-earned credits.", ['adult'], { happiness: 5, wealth: -300 }),
  E("A close friend borrowed a large sum and never paid it back.", ['adult'], { wealth: -200, happiness: -4 }),
  E("You took a long solo trip across the Outer Rim to clear your head.", ['adult'], { happiness: 6 }),
  E("A tax audit from the local government cost you dearly.", ['adult'], { wealth: -250, happiness: -3 }),
  E("You picked up a new hobby restoring an old astromech droid.", ['adult'], { happiness: 4, smarts: 2 }),
  E("You pulled an all-nighter finishing an important project.", ['adult'], { health: -3, smarts: 3 }),
  E("You invested in a promising cargo run and it paid off nicely.", ['adult'], { wealth: 500 }),
  E("A bar fight left you nursing a few bruises.", ['adult'], { health: -4 }),
  E("You started meditating daily and felt calmer for it.", ['adult'], { happiness: 4, health: 2 }),
  E("You caught a mild strain of Rodian flu going around the sector.", ['adult'], { health: -5 }),
  E("You took up a regular exercise routine and felt healthier for it.", ['adult'], { health: 5 }),
  E("A good harvest season left the whole settlement in high spirits.", ['adult'], { happiness: 4, health: 2 }),
  // ELDER
  E("You spent the afternoon telling wild stories to a crowd of young ones.", ['elder'], { happiness: 6 }),
  E("Old injuries ached more than they used to.", ['elder'], { health: -4 }),
  E("You finally finished writing your memoirs.", ['elder'], { happiness: 5, smarts: 2 }),
  E("You reconnected with an old friend you hadn't seen in decades.", ['elder'], { happiness: 7 }),
  E("A quiet, uneventful season passed by peacefully.", ['elder'], { happiness: 2 }),
  E("You passed down an old family heirloom to someone you love.", ['elder'], { happiness: 4 }),
];

const ERA_EVENTS = {
  'old-republic': [
    E("News reached you of a distant border skirmish between the Republic and a Sith remnant.", ['preteen','teen','adult','elder'], { happiness: -1 }),
    E("A Mandalorian warband passed through your system, trading rather than raiding — for once.", ['teen','adult'], { happiness: 1 }),
    E("You saw a Jedi envoy resolve a dispute in the town square without drawing a blade.", ['child','preteen','teen'], { smarts: 2 }),
  ],
  'fall-of-jedi': [
    E("Clone troop transports rumbled overhead on their way to a distant front.", ['child','preteen','teen','adult'], { happiness: -1 }),
    E("Separatist propaganda broadcasts crackled over the local holonet.", ['preteen','teen','adult'], { smarts: 1 }),
    E("A battle-weary clone trooper shared rations with your family during a supply shortage.", ['child','preteen','teen','adult'], { happiness: 2 }),
  ],
  'reign-of-empire': [
    E("An Imperial garrison set up a checkpoint in your town, and everyone kept their heads down.", ['child','preteen','teen','adult','elder'], { happiness: -2 }),
    E("Whispers spread of a Rebel Alliance striking Imperial convoys in the outer systems.", ['teen','adult'], { happiness: 1 }),
    E("Stormtroopers searched your home looking for smuggled goods.", ['preteen','teen','adult'], { happiness: -3 }),
  ],
  'new-republic-rise': [
    E("Celebrations broke out across the sector at news of the Emperor's defeat.", ['child','preteen','teen','adult','elder'], { happiness: 6 }),
    E("Remnant Imperial holdouts still caused trouble in nearby systems.", ['teen','adult'], { happiness: -1 }),
  ],
  'new-republic': [
    E("A New Republic relief convoy helped rebuild the local infrastructure.", ['child','preteen','teen','adult'], { happiness: 2 }),
    E("Stories spread of a New Jedi Order training a new generation on a hidden world.", ['child','preteen','teen'], { smarts: 1 }),
  ],
  'first-order-rise': [
    E("First Order recruitment banners appeared in the market square, unsettling everyone.", ['child','preteen','teen','adult'], { happiness: -2 }),
    E("Rumors spread of a Resistance movement standing against the First Order's rise.", ['teen','adult'], { happiness: 1 }),
  ],
  'new-jedi-order': [
    E("A pair of Jedi Knights passed through, keeping the peace without fanfare.", ['child','preteen','teen','adult'], { happiness: 2 }),
    E("Old Imperial war debris was finally cleared from the outskirts of town.", ['preteen','teen','adult'], { happiness: 1 }),
  ],
};

const CRIME_ACTIONS = [
  { text: "steal credits from a market stall", successChance: 0.6, successEffect: { wealth: 200, happiness: 2 }, failEffect: { happiness: -6, health: -5 } },
  { text: "pickpocket a wealthy traveler", successChance: 0.55, successEffect: { wealth: 350, happiness: 1 }, failEffect: { happiness: -8, wealth: -100 } },
  { text: "run contraband spice past a checkpoint", successChance: 0.45, successEffect: { wealth: 900, happiness: 3 }, failEffect: { happiness: -12, health: -10, wealth: -200 } },
  { text: "hack a bank's credit terminal", successChance: 0.4, successEffect: { wealth: 1500 }, failEffect: { happiness: -15, wealth: -300 } },
];
