/* ============================================================
   STAR WARS: A GALAXY LIFE — canon node system
   Absolute BBY/ABY timeline, Canon-Lock vs Legend mode,
   global events, origins, worlds, named characters, and
   flagship "replace the master" arcs.

   Years use the same convention as the source material: BBY is
   negative, ABY is positive, 0 is the Battle of Yavin (0 BBY and
   0 ABY are the same instant), so currentYear = birthYear + age
   works with plain integer arithmetic.

   ai_expand nodes from the design doc are hand-authored here
   (fixed branches) rather than generated by a live model, since
   this is a static site with no backend to safely call an LLM.
   ============================================================ */

const CANON_MODES = {
  CANON_LOCK: {
    id: 'CANON_LOCK',
    label: 'Canon Lock',
    blurb: 'The big beats always happen the way the films and shows say. You can be present at Order 66 or the Battle of Yavin, but you cannot change who lives or dies.',
  },
  LEGEND: {
    id: 'LEGEND',
    label: 'Legend Mode',
    blurb: 'You can replace canon figures — train Anakin, become the Emperor\'s apprentice, save someone who was never meant to live. The timeline re-branches around you.',
  },
};

/* Absolute birth windows, keyed to this game's existing flavor eras. */
const ABS_ERA_WINDOWS = {
  'old-republic': { birth: [-60, -33], ends: -19 },
  'fall-of-jedi': { birth: [-32, -22], ends: -19 },
  'reign-of-empire': { birth: [-21, 0], ends: 4 },
  'new-republic-rise': { birth: [5, 9], ends: 34 },
  'new-republic': { birth: [10, 25], ends: 34 },
  'first-order-rise': { birth: [15, 30], ends: 35 },
  'new-jedi-order': { birth: [31, 34], ends: 60 },
};

function rollBirthYear(eraId) {
  const w = ABS_ERA_WINDOWS[eraId];
  return randInt(w.birth[0], w.birth[1]);
}

/* ---------------- GLOBAL EVENTS ---------------- */
/* Fire on their real year, everywhere. Variant chosen by whether the
   player's current world matches `presentWorlds` (PRESENT), shares an
   era-appropriate region (NEARBY), or neither (DISTANT). */
const GLOBAL_EVENTS = [
  { id: 'GE_NABOO_INVASION', year: -32, label: 'The Trade Federation blockades Naboo', presentWorlds: ['Naboo'],
    present: "Trade Federation battle droids march through the streets. The Queen has vanished and a Gungan army is mustering in the swamps.",
    nearby: "Refugee ships from Naboo stream through the sector, fleeing a Trade Federation blockade.",
    distant: "The HoloNet carries grainy footage of a Trade Federation invasion fleet over Naboo.",
    effects: { happiness: -3 } },
  { id: 'GE_BOONTA_EVE', year: -32, label: 'Boonta Eve Podrace, Mos Espa', presentWorlds: ['Tatooine'],
    present: "The whole of Mos Espa turns out for the Boonta Eve Classic. A slave boy named Anakin is entered in the race — nobody's ever seen a human podrace before.",
    nearby: "Traders passing through talk about a slave-boy podracer who somehow finished the Boonta Eve Classic.",
    distant: "Sports channels on the HoloNet mention an upset finish at the Boonta Eve Classic on some Outer Rim backwater.",
    effects: { happiness: 3 } },
  { id: 'GE_GEONOSIS', year: -22, label: 'First Battle of Geonosis — the war begins', presentWorlds: ['Geonosis'],
    present: "The arena erupts into chaos as Jedi ignite their sabers and a droid army closes in. This is the day the Clone Wars begin.",
    nearby: "News breaks of a massive battle on Geonosis — clone troopers, Jedi, and thousands of battle droids.",
    distant: "The HoloNet declares war. The Galactic Republic has an army again, for the first time in a thousand generations.",
    effects: { happiness: -4 } },
  { id: 'GE_CHRISTOPHSIS', year: -22, label: 'Siege of Christophsis', presentWorlds: ['Christophsis'],
    present: "Deflector shields flare overhead as clone troopers dig in against Separatist artillery.",
    nearby: "Word spreads of a young Togruta Padawan assigned to General Skywalker on the Christophsis front.",
    distant: "Casualty reports from the Christophsis campaign scroll past on the news.",
    effects: { happiness: -2 } },
  { id: 'GE_ZILLO', year: -21, label: 'The Zillo Beast rampages through Coruscant', presentWorlds: ['Coruscant'],
    present: "A monstrous, armor-plated creature tears through the Senate district before clone troopers bring it down.",
    nearby: "Coruscant traffic control reroutes half the planet after some kind of giant beast attack in the capital.",
    distant: "A strange story about a giant reptilian creature rampaging through Coruscant makes the rounds on the HoloNet.",
    effects: { happiness: -2 } },
  { id: 'GE_MANDALORE_SIEGE', year: -19, label: 'Siege of Mandalore', presentWorlds: ['Mandalore', 'Concordia', 'Krownest'],
    present: "Republic gunships descend on Sundari as Ahsoka Tano and Bo-Katan Kryze move to finally bring down Maul's Shadow Collective.",
    nearby: "Reports of a Republic offensive to retake Mandalore from Maul's criminal empire filter through the sector.",
    distant: "The HoloNet mentions fighting on Mandalore, one of a hundred fronts in a war that never seems to end.",
    effects: { happiness: -2 } },
  { id: 'GE_ORDER_66', year: -19, label: 'Order 66', presentWorlds: [], forced: true,
    present: null, nearby: null, distant: null, effects: {} },
  { id: 'GE_MUSTAFAR', year: -19, label: 'The Battle of Mustafar', presentWorlds: ['Mustafar'],
    present: "Lava rivers light the sky as two blades clash in the mining complex. Whatever this is, it feels like the end of something.",
    nearby: "Rumors travel the Outer Rim of a Jedi duel fought to the death on a volcanic mining world.",
    distant: "The HoloNet announces the birth of the Galactic Empire the same week rumors spread of a Jedi betrayal.",
    effects: { happiness: -3 } },
  { id: 'GE_EMPIRE_DECLARED', year: -19, label: 'The Republic becomes the Empire', presentWorlds: ['Coruscant'],
    present: "Chancellor Palpatine addresses a packed Senate chamber. 'The Republic will be reorganized into the first Galactic Empire!' The applause is deafening.",
    nearby: "Imperial banners are already going up in the plaza by the time the broadcast ends.",
    distant: "Every channel on the HoloNet carries the same speech: the Republic is dead. Long live the Empire.",
    effects: { happiness: -2 } },
  { id: 'GE_KAMINO_BOMBED', year: -19, label: 'The Empire abandons the clone program', presentWorlds: ['Kamino'],
    present: "Imperial Star Destroyers open fire on the cloning facilities. The Kaminoans' usefulness has run out.",
    nearby: "Survivors from Kamino's bombing straggle into port, saying the Empire doesn't need clones anymore.",
    distant: "News trickles out that Kamino's cloning facilities were destroyed — the Empire prefers conscripts now.",
    effects: { happiness: -3 } },
  { id: 'GE_INQUISITORS_RISE', year: -18, label: 'The Inquisitorius begins hunting Jedi', presentWorlds: [],
    present: "A black-robed figure with a spinning double-bladed lightsaber has been asking questions about your world's Jedi.",
    nearby: "Word spreads to keep your head down — the Empire has started hunting down anyone connected to the Jedi.",
    distant: "Rumors describe red-bladed hunters scouring the Outer Rim for surviving Jedi.",
    effects: { happiness: -2 } },
  { id: 'GE_LOTHAL_REBELS', year: -5, label: 'The Ghost crew stirs up trouble on Lothal', presentWorlds: ['Lothal'],
    present: "A battered old freighter called the Ghost keeps humiliating the local Imperial garrison. The crew's becoming folk heroes.",
    nearby: "Stories spread about a rebel cell on Lothal giving the Empire real trouble.",
    distant: "An Imperial bulletin lists a Lothal-based rebel cell as a growing nuisance.",
    effects: { happiness: 1 } },
  { id: 'GE_GHORMAN_MASSACRE', year: -2, label: 'The Ghorman Massacre', presentWorlds: ['Ghorman'],
    present: "Imperial troops open fire on a peaceful protest in the town square. The images will never leave you.",
    nearby: "Refugees from Ghorman arrive with stories of Imperial troops firing into an unarmed crowd.",
    distant: "The Empire's official broadcast blames 'rebel terrorists' for violence on Ghorman. You aren't sure you believe it.",
    effects: { happiness: -6 } },
  { id: 'GE_JEDHA', year: 0, label: 'The Death Star tests its weapon on Jedha City', presentWorlds: ['Jedha'],
    present: "The horizon turns white. Jedha City — and everyone in it — is simply gone a moment later.",
    nearby: "A green-white flash lights up half the system before the news arrives: Jedha City has been erased.",
    distant: "The Empire denies any 'incident' on Jedha, but the HoloNet is full of terrified rumors about a new superweapon.",
    effects: { happiness: -6 }, instantDeathIfPresentUnlessFlag: 'left_jedha_early' },
  { id: 'GE_ALDERAAN', year: 0, label: 'Alderaan is destroyed', presentWorlds: ['Alderaan'],
    present: "There is no warning. There is no time. Alderaan, and everyone on it, ceases to exist.",
    nearby: "A wave of debris and radiation rolls through the system. Alderaan is gone. It is simply gone.",
    distant: "The HoloNet goes silent on the subject for hours before finally confirming it: Alderaan has been destroyed.",
    effects: { happiness: -10 }, instantDeathIfPresent: true },
  { id: 'GE_SCARIF', year: 0, label: 'The Battle of Scarif', presentWorlds: ['Scarif'],
    present: "Rebel and Imperial fleets tear each other apart in orbit while a desperate team tries to steal the Death Star's plans from the vault below.",
    nearby: "News of a Rebel strike on the Imperial data vault at Scarif spreads through the fleet.",
    distant: "The Empire reports 'a contained security incident' at a facility called Scarif.",
    effects: { happiness: -2 } },
  { id: 'GE_YAVIN', year: 0, label: 'The Battle of Yavin', presentWorlds: ['Yavin 4'],
    present: "Red and gold squadrons scream down the Death Star's trench. Everything comes down to one impossible shot.",
    nearby: "A Rebel fleet has gathered near Yavin. Something big is about to happen.",
    distant: "The HoloNet reports the destruction of an Imperial 'battle station' — and calls the Rebellion's survival a miracle.",
    effects: { happiness: 4 } },
  { id: 'GE_HOTH', year: 3, label: 'The Battle of Hoth', presentWorlds: ['Hoth'],
    present: "AT-AT walkers crest the ridge above Echo Base. The evacuation klaxons are already screaming.",
    nearby: "Rebel transports fleeing an ice world limp into port, shot half to pieces.",
    distant: "Imperial propaganda claims total victory over a 'Rebel terrorist base' on some frozen nowhere world.",
    effects: { happiness: -3 } },
  { id: 'GE_BESPIN', year: 3, label: 'Betrayal at Cloud City', presentWorlds: ['Bespin'],
    present: "Cloud City's Baron Administrator makes a deal with the Empire, and a carbon-freezing chamber hisses open.",
    nearby: "Cloud City goes quiet on the comm networks for two full days. Something happened there.",
    distant: "Rumors say the Empire leaned on a Cloud City administrator to hand over some Rebel fugitives.",
    effects: { happiness: -2 } },
  { id: 'GE_JABBA_DEATH', year: 4, label: "Jabba the Hutt dies aboard his sail barge", presentWorlds: ['Tatooine'],
    present: "The sail barge erupts into fire over the Great Pit of Carkoon. By nightfall, word is already spreading: Jabba the Hutt is dead.",
    nearby: "Hutt enforcers are suddenly nervous — Jabba's dead, and everyone's rearranging their loyalties.",
    distant: "The criminal underworld buzzes with news that one of the galaxy's most powerful Hutts has been killed.",
    effects: { happiness: 1 } },
  { id: 'GE_ENDOR', year: 4, label: 'The Battle of Endor', presentWorlds: ['Endor'],
    present: "A second Death Star burns in the sky above the forest moon as Ewoks and Rebel commandos fight through the shield bunker.",
    nearby: "A Rebel fleet has massed near Endor to strike at a second, still-unfinished battle station.",
    distant: "Every HoloNet channel breaks with the same news: the Emperor is dead, and the second Death Star has been destroyed.",
    effects: { happiness: 8 } },
  { id: 'GE_JAKKU', year: 5, label: "The Battle of Jakku — the Empire's last stand", presentWorlds: ['Jakku'],
    present: "Star Destroyers fall burning from the sky as the last real Imperial fleet is broken over Jakku's dunes.",
    nearby: "Refugee convoys stream away from Jakku, fleeing what's shaping up to be the war's final battle.",
    distant: "The HoloNet declares the Galactic Civil War effectively over after a decisive battle at a world called Jakku.",
    effects: { happiness: 5 } },
  { id: 'GE_THRAWN_RETURNS', year: 9, label: 'Ahsoka Tano searches for Grand Admiral Thrawn', presentWorlds: ['Lothal', 'Peridea'],
    present: "A former Jedi and a Mandalorian artist are hunting for a map through hyperspace to a world beyond the known galaxy.",
    nearby: "Word travels that Thrawn, the Empire's most dangerous strategist, may not be as dead as everyone hoped.",
    distant: "Old spacers still trade rumors about the fate of Grand Admiral Thrawn, vanished since the war's end.",
    effects: { happiness: -1 } },
  { id: 'GE_LUKE_TEMPLE', year: 20, label: "Luke Skywalker's Jedi academy", presentWorlds: [],
    present: "Word has reached you: Luke Skywalker is training a new generation of Jedi, somewhere out past the Core.",
    nearby: "A neighbor's Force-sensitive child was quietly sent off-world to study with a Jedi Master.",
    distant: "Rumors persist of a new Jedi Order being rebuilt, decades after the Empire tried to erase the old one.",
    effects: { happiness: 2 } },
  { id: 'GE_TEMPLE_BURNS', year: 28, label: "Luke's Jedi temple falls", presentWorlds: [],
    present: "Fire lights the night sky over the temple grounds. Something has gone horribly wrong among Luke Skywalker's students.",
    nearby: "Survivors from a burned Jedi temple pass through, unwilling to talk about what happened.",
    distant: "Rumors spread that Luke Skywalker's new Jedi Order has collapsed in fire and betrayal.",
    effects: { happiness: -5 } },
  { id: 'GE_HOSNIAN', year: 34, label: 'Starkiller Base fires on the Hosnian system', presentWorlds: ['Hosnian Prime'],
    present: "The sky itself seems to catch fire. There is no more Hosnian Prime, and no more New Republic government.",
    nearby: "A star that shouldn't exist blooms in the sky before the news arrives: the Hosnian system is gone.",
    distant: "The HoloNet dies mid-broadcast. Every channel from the Hosnian system has gone silent, all at once.",
    effects: { happiness: -10 }, instantDeathIfPresent: true },
  { id: 'GE_STARKILLER_ASSAULT', year: 34, label: 'The Resistance strikes Starkiller Base', presentWorlds: ['Starkiller Base'],
    present: "Resistance fighters scream in low over an ice planet the size of a small moon, racing to destroy it before it fires again.",
    nearby: "A ragtag Resistance fleet is massing to hit the weapon that destroyed the Hosnian system.",
    distant: "The HoloNet — what's left of it — reports a Resistance strike against the First Order's superweapon.",
    effects: { happiness: 3 } },
  { id: 'GE_CRAIT', year: 34, label: 'The last stand on Crait', presentWorlds: ['Crait'],
    present: "A First Order battering-ram cannon crawls across a field of red salt toward the last of the Resistance.",
    nearby: "What's left of the Resistance fleet is said to be cornered somewhere near a mining world called Crait.",
    distant: "The First Order claims to have crushed the Resistance's last remnant at some Outer Rim mining outpost.",
    effects: { happiness: -3 } },
  { id: 'GE_EXEGOL', year: 35, label: 'The Battle of Exegol', presentWorlds: ['Exegol'],
    present: "A hidden Sith fleet the size of a small armada rises out of the fog on a world that isn't supposed to exist.",
    nearby: "An impossible call goes out across every frequency: a call for help against a fleet that shouldn't exist.",
    distant: "The HoloNet is calling it the Battle of Exegol — the day the Emperor came back, and the day he finally died for good.",
    effects: { happiness: 6 } },
];

/* ---------------- ORIGINS ---------------- */
const ORIGINS = [
  { id: 'OR_MOISTURE_FARMER', label: 'Moisture farm kid', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-jedi-order'], worlds: ['Tatooine'], flags: ['poor'],
    text: "You grew up hauling vaporator parts under twin suns, dreaming about the ships that passed overhead." },
  { id: 'OR_SLAVE_HUTT', label: 'Hutt-owned slave', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Tatooine', 'Nal Hutta', 'Nar Shaddaa'], flags: ['slave', 'explosive_chip', 'poor'],
    text: "You were born property. A chip was implanted at your first breath — insurance against ever trying to run." },
  { id: 'OR_SLAVE_ZYGERRIAN', label: 'Zygerrian slave market', eras: ['fall-of-jedi'], worlds: ['Zygerria'], flags: ['slave'],
    text: "You were sold at auction on Zygerria before you were old enough to remember your parents' faces." },
  { id: 'OR_CORELLIAN_STREET', label: 'Corellian scrumrat', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-jedi-order'], worlds: ['Corellia'], flags: ['criminal'],
    text: "You ran with a street gang in Coronet City, learning to pick pockets before you learned to read." },
  { id: 'OR_NABOO_ROYAL', label: 'Naboo noble house', eras: ['old-republic', 'fall-of-jedi'], worlds: ['Naboo'], flags: ['wealthy', 'political'],
    text: "You were raised in a house of Naboo nobility, all silk robes and Theed's marble courtyards." },
  { id: 'OR_SENATOR_CHILD', label: "Senator's child", eras: ['old-republic', 'fall-of-jedi', 'new-republic-rise', 'new-republic'], worlds: ['Coruscant', 'Alderaan', 'Chandrila'], flags: ['wealthy', 'political'],
    text: "You grew up in the shadow of the Senate rotunda, half politician's child, half hostage to your parent's career." },
  { id: 'OR_CORUSCANT_UNDERLEVEL', label: 'Coruscant underlevel gang kid', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: ['Coruscant'], flags: ['criminal', 'poor'],
    text: "You were raised a thousand levels below the Senate's skyline, where sunlight is a rumor." },
  { id: 'OR_MANDO_FOUNDLING', label: 'Mandalorian foundling', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'new-jedi-order'], worlds: ['Mandalore', 'Concordia', 'Nevarro'], flags: ['mandalorian'],
    text: "A clan found you, alone and starving, and raised you in the Creed. This is the Way." },
  { id: 'OR_WOOKIEE_LIFEDEBT', label: 'Born on Kashyyyk', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Kashyyyk'], flags: ['wookiee_home', 'strong'],
    text: "You grew up in the wroshyr treetops of Kashyyyk, where a life-debt is sacred and Trandoshan slavers are a very old fear." },
  { id: 'OR_TWILEK_RYLOTH', label: 'Ryloth clan child', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Ryloth'], flags: ['twilek_home'],
    text: "You grew up in the canyon clans of Ryloth, where every generation remembers slavers coming from orbit." },
  { id: 'OR_NIGHTSISTER', label: 'Dathomir witch coven', eras: ['old-republic', 'fall-of-jedi'], worlds: ['Dathomir'], flags: ['force_sensitive', 'dark_magick'],
    text: "The Nightsisters raised you on Dathomir's magick — spirit-song, ichor, and a mother who was more myth than woman." },
  { id: 'OR_NIGHTBROTHER', label: 'Zabrak of Dathomir', eras: ['old-republic', 'fall-of-jedi'], worlds: ['Dathomir'], flags: ['force_sensitive', 'warrior'],
    text: "You were raised among the Nightbrothers, trained for the selection trials that decide who is worth keeping alive." },
  { id: 'OR_PIRATE_BORN', label: "Raised by Hondo Ohnaka's crew", eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: [], flags: ['pirate'],
    text: "You grew up aboard a pirate crew that answered, loosely, to Hondo Ohnaka — profitable chaos, mostly." },
  { id: 'OR_SMUGGLER_BORN', label: 'Born on a freighter', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise', 'new-jedi-order'], worlds: [], flags: ['pilot'],
    text: "You were born between hyperspace jumps and never really had a homeworld — just a ship, and a horizon that kept moving." },
  { id: 'OR_SPACER_ORPHAN', label: 'Station orphan', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: ['Nar Shaddaa'], flags: ['poor'],
    text: "You grew up scavenging a space station's lower decks, one step ahead of station security." },
  { id: 'OR_GUNGAN', label: 'Gungan of Otoh Gunga', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Naboo'], flags: ['gungan_home'],
    text: "You grew up in Otoh Gunga's bubble city beneath Naboo's lakes, half-suspicious of the surface-dwellers above." },
  { id: 'OR_MON_CALA', label: 'Mon Calamari shipwright family', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: ['Mon Cala'], flags: ['aquatic'],
    text: "You grew up in Mon Cala's coral cities, surrounded by a family trade in starship hulls." },
  { id: 'OR_JEDHA_PILGRIM', label: 'Guardian of the Whills family', eras: ['reign-of-empire'], worlds: ['Jedha'], flags: ['spiritual', 'force_adjacent'],
    text: "Your family kept the old ways in Jedha City, watching over the temple ruins long after the Jedi were gone." },
  { id: 'OR_HUTT_CLAN', label: 'Born into a Hutt family', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: ['Nal Hutta'], flags: ['hutt', 'wealthy', 'criminal'],
    text: "You were born into a Hutt kajidic, wealthy and untouchable and thoroughly corrupt from birth." },
  { id: 'OR_BOUNTY_FAMILY', label: "Child of a Guild hunter", eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic', 'new-jedi-order'], worlds: [], flags: ['hunter'],
    text: "Your parent hunted for the Bounty Hunters' Guild, and you grew up around blaster maintenance and unpaid debts." },
  { id: 'OR_ALDERAAN_NOBLE', label: 'House of Alderaan minor nobility', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Alderaan'], flags: ['wealthy', 'pacifist'],
    text: "You were raised in the gentle, pacifist courts of Alderaan, where even the nobility learn diplomacy before dueling." },
  { id: 'OR_KAMINOAN_CLONE', label: 'Clone (Jango Fett template)', eras: ['fall-of-jedi'], worlds: ['Kamino'], flags: ['clone', 'accelerated_aging', 'chip'],
    text: "You were decanted on Kamino, one of untold thousands grown from the same template, aging twice as fast as anyone born the old way." },
  { id: 'OR_JEDI_YOUNGLING', label: 'Taken to the Jedi Temple as an infant', eras: ['old-republic', 'fall-of-jedi'], worlds: ['Coruscant'], flags: ['force_sensitive', 'jedi'],
    text: "Jedi Knights came for you before you could walk, sensing something in you through the Force. The Temple raised you instead of any family." },
  { id: 'OR_BORN_TO_JEDI', label: 'Secret child of a Jedi', eras: ['old-republic', 'fall-of-jedi'], worlds: ['Coruscant'], flags: ['force_sensitive', 'jedi_secret'],
    text: "One of your parents was a Jedi who broke the Code to have you. The Council looks the other way, quietly, for now.", legendOnly: true },
  { id: 'OR_SEPARATIST_WORLD', label: 'Born a Separatist citizen', eras: ['fall-of-jedi'], worlds: ['Geonosis', 'Raxus', 'Serenno'], flags: ['separatist'],
    text: "You grew up under the Confederacy's banner, taught that the Republic was the villain in this war." },
  { id: 'OR_IMPERIAL_OFFICER_CHILD', label: 'Imperial officer family', eras: ['reign-of-empire'], worlds: ['Coruscant', 'Eriadu'], flags: ['imperial', 'wealthy'],
    text: "Your parent wore an Imperial uniform, and dinner conversation revolved around promotions and 'necessary' crackdowns." },
  { id: 'OR_STORMTROOPER_CONSCRIPT', label: 'Conscripted for the stormtrooper corps', eras: ['reign-of-empire'], worlds: [], flags: ['trooper'],
    text: "Imperial recruiters took you from an Outer Rim backwater at fifteen. Nobody asked if you wanted to go." },
  { id: 'OR_REBEL_CELL_CHILD', label: "Child of Rebel partisans", eras: ['reign-of-empire'], worlds: [], flags: ['rebel', 'hunted'],
    text: "Your parents fought the Empire in the shadows, and you grew up learning which neighbors could be trusted." },
  { id: 'OR_HIDDEN_JEDI_WARD', label: 'Raised by a Jedi in hiding', eras: ['reign-of-empire'], worlds: [], flags: ['force_sensitive', 'hunted'],
    text: "A Jedi who survived the Purge took you in and taught you, quietly, to hide what you are." },
  { id: 'OR_LOTHAL_STREET', label: 'Lothal street orphan', eras: ['reign-of-empire'], worlds: ['Lothal'], flags: ['poor'],
    text: "You grew up stealing from Imperial supply convoys on Lothal, just trying to eat." },
  { id: 'OR_GHORMAN_WEAVER', label: 'Ghorman weaver family', eras: ['reign-of-empire'], worlds: ['Ghorman'], flags: ['pacifist'],
    text: "Your family wove Ghorman cloth for generations, proud and stubborn and increasingly afraid of the Empire's interest in your world." },
  { id: 'OR_ALDERAAN_REFUGEE_CHILD', label: 'Alderaanian refugee family', eras: ['reign-of-empire'], worlds: [], flags: ['refugee'],
    text: "Your parents left Alderaan before it was destroyed. You grew up in the space between grief and survivor's guilt that was never quite yours." },
  { id: 'OR_INQUISITOR_CANDIDATE', label: 'Force child taken by the Inquisitorius', eras: ['reign-of-empire'], worlds: [], flags: ['inquisitor_trainee', 'dark'],
    text: "The Inquisitorius found you young, and Fortress Inquisitorius on Nur raised you to hunt your own kind.", legendOnly: true },
  { id: 'OR_JAKKU_SCAVENGER', label: 'Niima Outpost scavenger', eras: ['new-republic', 'first-order-rise'], worlds: ['Jakku'], flags: ['poor'],
    text: "You strip Imperial wreckage for portions under Unkar Plutt's thumb at Niima Outpost." },
  { id: 'OR_NEW_REPUBLIC_OFFICER_CHILD', label: 'New Republic political family', eras: ['new-republic-rise', 'new-republic'], worlds: ['Chandrila', 'Hosnian Prime'], flags: ['wealthy', 'political'],
    text: "Your family helped build the New Republic Senate from the Empire's ashes, and you grew up in its halls." },
  { id: 'OR_LUKES_STUDENT', label: "Sent to Luke Skywalker's temple", eras: ['new-republic', 'new-jedi-order'], worlds: [], flags: ['force_sensitive', 'jedi'],
    text: "You were sent, young and frightened, to study under Luke Skywalker at his new Jedi temple." },
  { id: 'OR_MANDO_COVERT', label: 'Child of the Watch', eras: ['new-republic-rise', 'new-republic', 'new-jedi-order'], worlds: ['Nevarro', 'Mandalore'], flags: ['mandalorian', 'never_remove_helmet'],
    text: "You were raised in a covert of the Children of the Watch, and no one outside your clan has ever seen your face." },
  { id: 'OR_IMPERIAL_REMNANT_CHILD', label: 'Raised on a hidden Star Destroyer', eras: ['new-republic-rise', 'new-republic'], worlds: [], flags: ['imperial_remnant'],
    text: "You grew up aboard a Star Destroyer that never surrendered, raised on stories that the Empire would rise again." },
  { id: 'OR_FO_STORMTROOPER_TAKEN', label: 'Taken at birth by the First Order', eras: ['first-order-rise'], worlds: [], flags: ['fo_trooper', 'no_name'],
    text: "The First Order took you as an infant and gave you a number instead of a name. You've never known anything else." },
  { id: 'OR_FO_OFFICER_CHILD', label: 'First Order officer family', eras: ['first-order-rise'], worlds: [], flags: ['first_order', 'wealthy'],
    text: "You were raised aboard a Star Destroyer, taught that the New Republic's peace was a weakness waiting to be corrected." },
  { id: 'OR_RESISTANCE_CHILD', label: "Child of Leia's Resistance", eras: ['first-order-rise'], worlds: [], flags: ['resistance'],
    text: "Your parents joined General Organa's Resistance back when almost nobody believed the First Order was a real threat." },
  { id: 'OR_KIJIMI_THIEF', label: "Zorii Bliss's Spice Runners", eras: ['first-order-rise'], worlds: ['Kijimi'], flags: ['criminal'],
    text: "You grew up running spice through Kijimi's frozen streets with the Spice Runners, sharp-eyed and quick-fingered." },
  { id: 'OR_EXEGOL_CULTIST', label: 'Born into the Sith Eternal cult', eras: ['first-order-rise'], worlds: ['Exegol'], flags: ['sith_eternal', 'dark'],
    text: "You were raised chanting in the dark on a world that officially doesn't exist, waiting for an Emperor everyone assumed was dead.", legendOnly: true },
  { id: 'OR_BATUU_OUTPOST', label: 'Black Spire Outpost native', eras: ['new-republic', 'first-order-rise', 'new-jedi-order'], worlds: ['Batuu'], flags: [],
    text: "You grew up in Black Spire Outpost, where smugglers, First Order officers, and Resistance sympathizers all drink at the same cantina." },
];

/* ---------------- WORLDS ---------------- */
const CANON_WORLDS = [
  { name: 'Coruscant', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise', 'new-jedi-order'], bonus: { smarts: 4 }, exitRoutes: ['Senate posting', 'Jedi transfer', 'Navy enlistment', 'smuggling run'] },
  { name: 'Alderaan', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], bonus: { looks: 3, smarts: 2 }, exitRoutes: ['Senate aide posting', 'Rebel courier route', 'university abroad'] },
  { name: 'Corellia', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], bonus: {}, exitRoutes: ['Imperial Navy enlistment', 'CEC shipwright apprenticeship', 'smuggler crew'] },
  { name: 'Chandrila', eras: ['new-republic-rise', 'new-republic', 'first-order-rise'], bonus: { looks: 2 }, exitRoutes: ['New Republic politics', 'NR fleet enlistment'] },
  { name: 'Naboo', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: { looks: 3 }, exitRoutes: ['Royal Guard', 'N-1 pilot training', 'Senate posting'] },
  { name: 'Kashyyyk', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: { health: 4 }, exitRoutes: ['life-debt to an offworlder', 'Republic army enlistment', 'Rebellion contact'] },
  { name: 'Ryloth', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic'], bonus: { looks: 2 }, exitRoutes: ['freedom fighter cell', 'Republic evacuation convoy'] },
  { name: 'Mon Cala', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic'], bonus: {}, exitRoutes: ['Republic/Rebel fleet enlistment'] },
  { name: 'Kamino', eras: ['fall-of-jedi'], bonus: { smarts: 2 }, exitRoutes: ['clone deployment'] },
  { name: 'Dathomir', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], bonus: {}, exitRoutes: ["sold off-world", "Maul's Shadow Collective"] },
  { name: 'Mandalore', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: {}, exitRoutes: ['bounty hunting contract', "Death Watch raid", 'reclamation campaign'] },
  { name: 'Geonosis', eras: ['fall-of-jedi', 'reign-of-empire'], bonus: { smarts: 2 }, exitRoutes: ['CIS droid factory work', 'Imperial construction contract'] },
  { name: 'Mustafar', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], bonus: {}, exitRoutes: ['mining contract'] },
  { name: 'Jedha', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], bonus: {}, exitRoutes: ["pilgrim's route", "Saw's Partisans"] },
  { name: 'Jakku', eras: ['reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], bonus: { health: 2 }, exitRoutes: ['salvage freighter', 'Resistance recruiter', 'First Order patrol'] },
  { name: 'Nevarro', eras: ['new-republic-rise', 'new-republic', 'first-order-rise'], bonus: {}, exitRoutes: ['Bounty Guild contract'] },
  { name: 'Batuu', eras: ['new-republic', 'first-order-rise'], bonus: {}, exitRoutes: ['any passing freighter'] },
  { name: 'Tatooine', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], bonus: { health: 2 }, exitRoutes: ['podrace winnings', 'smuggler crew', "Jabba's service"] },
  { name: 'Nal Hutta', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: {}, exitRoutes: ['bounty contract', 'smuggler run'] },
  { name: 'Hoth', eras: ['reign-of-empire'], bonus: { health: 2 }, exitRoutes: ['Rebel transport'] },
  { name: 'Bespin', eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: { smarts: 2 }, exitRoutes: ['gas freighter crew'] },
  { name: 'Endor', eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: {}, exitRoutes: ['Rebel fleet contact'] },
  { name: 'Lothal', eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], bonus: {}, exitRoutes: ['Imperial Academy', "Ghost crew"] },
];

/* ---------------- NAMED CHARACTERS ---------------- */
/* birthYear: null = ageless / effectively always adult for romance purposes.
   deathYear: null = no fixed canon death shown; protected in CANON_LOCK by default. */
const CHARACTERS = [
  { id: 'yoda', name: 'Yoda', birthYear: -896, deathYear: 4, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Coruscant', 'Dagobah'], verbs: { meet: true, train: 'under', date: false, fight: 'spar' } },
  { id: 'mace_windu', name: 'Mace Windu', birthYear: -72, deathYear: -19, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Coruscant'], verbs: { meet: true, train: 'under', date: false, fight: 'spar' } },
  { id: 'qui_gon', name: 'Qui-Gon Jinn', birthYear: -80, deathYear: -32, eras: ['old-republic'], worlds: ['Coruscant', 'Naboo', 'Tatooine'], verbs: { meet: true, train: 'under', date: false, fight: false } },
  { id: 'obi_wan', name: 'Obi-Wan Kenobi', birthYear: -57, deathYear: 0, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Coruscant', 'Naboo', 'Tatooine'], verbs: { meet: true, train: 'under', date: false, fight: 'spar' } },
  { id: 'anakin', name: 'Anakin Skywalker', birthYear: -41, deathYear: 4, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Tatooine', 'Coruscant'], verbs: { meet: true, train: 'under', date: 'forbidden', fight: 'spar' } },
  { id: 'padme', name: 'Padmé Amidala', birthYear: -46, deathYear: -19, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Naboo', 'Coruscant'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'dooku', name: 'Count Dooku', birthYear: -102, deathYear: -19, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Serenno', 'Geonosis'], verbs: { meet: true, train: 'under', date: false, fight: 'duel' } },
  { id: 'maul', name: 'Darth Maul', birthYear: -54, deathYear: 5, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Dathomir', 'Mandalore'], verbs: { meet: true, train: false, date: false, fight: 'duel' } },
  { id: 'ventress', name: 'Asajj Ventress', birthYear: -50, deathYear: -19, eras: ['fall-of-jedi'], worlds: ['Dathomir', 'Nar Shaddaa'], verbs: { meet: true, train: 'under', date: true, fight: 'duel' } },
  { id: 'ahsoka', name: 'Ahsoka Tano', birthYear: -36, deathYear: null, eras: ['fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Coruscant', 'Mandalore', 'Lothal'], verbs: { meet: true, train: 'under', date: true, fight: 'spar' } },
  { id: 'rex', name: 'Captain Rex', birthYear: -32, deathYear: null, eras: ['fall-of-jedi', 'reign-of-empire', 'new-republic-rise'], worlds: ['Kashyyyk', 'Lothal', 'Endor'], verbs: { meet: true, train: false, date: false, fight: 'spar' } },
  { id: 'palpatine', name: 'Sheev Palpatine', birthYear: -82, deathYear: 35, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'first-order-rise'], worlds: ['Coruscant', 'Exegol'], verbs: { meet: true, train: 'under', date: false, fight: false } },
  { id: 'grievous', name: 'General Grievous', birthYear: -68, deathYear: -19, eras: ['fall-of-jedi'], worlds: ['Utapau', 'Dathomir'], verbs: { meet: true, train: false, date: false, fight: 'duel' } },
  { id: 'jango', name: 'Jango Fett', birthYear: -66, deathYear: -22, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Kamino', 'Geonosis'], verbs: { meet: true, train: false, date: false, fight: 'duel' } },
  { id: 'boba', name: 'Boba Fett', birthYear: -32, deathYear: null, eras: ['fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Kamino', 'Tatooine'], verbs: { meet: true, train: false, date: false, fight: 'duel' } },
  { id: 'hondo', name: 'Hondo Ohnaka', birthYear: -60, deathYear: null, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic'], worlds: ['Florrum', 'Batuu'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'satine', name: 'Duchess Satine', birthYear: -58, deathYear: -20, eras: ['old-republic', 'fall-of-jedi'], worlds: ['Mandalore'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'bo_katan', name: 'Bo-Katan Kryze', birthYear: -55, deathYear: null, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Mandalore', 'Nevarro'], verbs: { meet: true, train: 'under', date: true, fight: 'duel' } },
  { id: 'saw_gerrera', name: 'Saw Gerrera', birthYear: -55, deathYear: 0, eras: ['fall-of-jedi', 'reign-of-empire'], worlds: ['Onderon', 'Jedha'], verbs: { meet: true, train: 'under', date: false, fight: false } },
  { id: 'bail_organa', name: 'Bail Organa', birthYear: -75, deathYear: 0, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Alderaan', 'Coruscant'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'mon_mothma', name: 'Mon Mothma', birthYear: -68, deathYear: null, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Coruscant', 'Chandrila'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'jabba', name: 'Jabba the Hutt', birthYear: -600, deathYear: 4, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire'], worlds: ['Tatooine', 'Nal Hutta'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'maz', name: 'Maz Kanata', birthYear: -1000, deathYear: null, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], worlds: ['Takodana'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'chewbacca', name: 'Chewbacca', birthYear: -200, deathYear: null, eras: ['old-republic', 'fall-of-jedi', 'reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], worlds: ['Kashyyyk'], verbs: { meet: true, train: false, date: false, fight: 'spar' } },
  { id: 'vader', name: 'Darth Vader', birthYear: -41, deathYear: 4, eras: ['reign-of-empire'], worlds: ['Coruscant', 'Mustafar'], verbs: { meet: true, train: 'under', date: false, fight: 'duel' } },
  { id: 'tarkin', name: 'Grand Moff Tarkin', birthYear: -64, deathYear: 0, eras: ['reign-of-empire'], worlds: ['Eriadu', 'Coruscant'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'thrawn', name: 'Grand Admiral Thrawn', birthYear: -56, deathYear: null, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Lothal'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'kanan', name: 'Kanan Jarrus', birthYear: -34, deathYear: -1, eras: ['reign-of-empire'], worlds: ['Lothal'], verbs: { meet: true, train: 'under', date: false, fight: 'spar' } },
  { id: 'hera', name: 'Hera Syndulla', birthYear: -34, deathYear: null, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Ryloth', 'Lothal'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'ezra', name: 'Ezra Bridger', birthYear: -19, deathYear: null, eras: ['reign-of-empire', 'new-republic'], worlds: ['Lothal'], verbs: { meet: true, train: 'under', date: true, fight: 'spar' } },
  { id: 'sabine', name: 'Sabine Wren', birthYear: -20, deathYear: null, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Mandalore', 'Lothal'], verbs: { meet: true, train: false, date: true, fight: 'spar' } },
  { id: 'jyn_erso', name: 'Jyn Erso', birthYear: -21, deathYear: 0, eras: ['reign-of-empire'], worlds: ['Jedha'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'cassian', name: 'Cassian Andor', birthYear: -22, deathYear: 0, eras: ['reign-of-empire'], worlds: ['Ferrix'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'han_solo', name: 'Han Solo', birthYear: -32, deathYear: 34, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Corellia'], verbs: { meet: true, train: false, date: false, fight: false } },
  { id: 'lando', name: 'Lando Calrissian', birthYear: -31, deathYear: null, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], worlds: ['Bespin'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'luke', name: 'Luke Skywalker', birthYear: -19, deathYear: 34, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic'], worlds: ['Tatooine', 'Yavin 4'], verbs: { meet: true, train: 'under', date: false, fight: 'spar' } },
  { id: 'leia', name: 'Leia Organa', birthYear: -19, deathYear: 35, eras: ['reign-of-empire', 'new-republic-rise', 'new-republic', 'first-order-rise'], worlds: ['Alderaan', 'Yavin 4'], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'din_djarin', name: 'Din Djarin', birthYear: -19, deathYear: null, eras: ['new-republic-rise', 'new-republic'], worlds: ['Nevarro', 'Mandalore'], verbs: { meet: true, train: false, date: true, fight: 'duel' } },
  { id: 'grogu', name: 'Grogu', birthYear: -41, deathYear: null, eras: ['new-republic-rise', 'new-republic'], worlds: ['Nevarro'], verbs: { meet: true, train: 'either', date: false, fight: false } },
  { id: 'moff_gideon', name: 'Moff Gideon', birthYear: -30, deathYear: null, eras: ['new-republic-rise', 'new-republic'], worlds: ['Nevarro', 'Mandalore'], verbs: { meet: true, train: false, date: false, fight: 'duel' } },
  { id: 'ben_solo', name: 'Ben Solo', birthYear: 5, deathYear: 35, eras: ['new-republic'], worlds: [], verbs: { meet: true, train: 'either', date: false, fight: 'duel' } },
  { id: 'rey', name: 'Rey', birthYear: 15, deathYear: null, eras: ['new-republic', 'first-order-rise'], worlds: ['Jakku'], verbs: { meet: true, train: 'either', date: true, fight: 'spar' } },
  { id: 'kylo_ren', name: 'Kylo Ren', birthYear: 5, deathYear: 35, eras: ['first-order-rise'], worlds: [], verbs: { meet: true, train: 'either', date: false, fight: 'duel' } },
  { id: 'finn', name: 'Finn', birthYear: 11, deathYear: null, eras: ['first-order-rise'], worlds: [], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'poe', name: 'Poe Dameron', birthYear: 2, deathYear: null, eras: ['first-order-rise'], worlds: [], verbs: { meet: true, train: false, date: true, fight: false } },
  { id: 'snoke', name: 'Supreme Leader Snoke', birthYear: null, deathYear: 34, eras: ['first-order-rise'], worlds: [], verbs: { meet: true, train: 'under', date: false, fight: false } },
];

function characterAgeAtYear(character, year) {
  if (character.birthYear === null) return 999;
  return year - character.birthYear;
}
function canRomanceCharacter(playerAge, playerCanonMode, character, currentYear) {
  if (playerAge < 18) return false;
  if (!character.verbs.date) return false;
  if (character.verbs.date === 'forbidden' && playerCanonMode === 'CANON_LOCK') return false;
  return characterAgeAtYear(character, currentYear) >= 18;
}
function canKillCharacter(character, canonMode, currentYear) {
  if (canonMode === 'LEGEND') return true;
  if (character.deathYear === null) return false;
  return character.deathYear <= currentYear;
}

/* ---------------- FLAGSHIP LEGEND ARCS ---------------- */
/* Each arc is an ordered list of beats. A beat fires when its `year`
   matches the player's current absolute year and the previous beat
   (if any) has been resolved. Legend-only; requires canonMode LEGEND
   and the listed trigger flag. */
const LEGEND_ARCS = {
  ARC_MASTER_ANAKIN: {
    label: "Master Anakin Skywalker",
    triggerFlags: ['jedi_knight'],
    triggerYear: -32,
    beats: [
      { year: -32, title: 'A Padawan for a New Knight',
        text: "The Council chamber is quiet. Obi-Wan Kenobi has just been knighted, but Qui-Gon Jinn's dying wish was that a nine-year-old named Anakin Skywalker be trained. Master Yoda turns to you.",
        options: [
          { label: 'Accept the padawan', effects: { flags_add: ['master_of_anakin'], alignment: 5 }, log: "You accepted Anakin Skywalker as your Padawan learner, against the Council's private misgivings." },
          { label: 'Refuse; let Obi-Wan take him', effects: {}, log: "You declined. Obi-Wan took the boy instead, and history proceeds without you." },
        ] },
      { year: -22, title: "Shmi's Dream", requiresFlag: 'master_of_anakin',
        text: "Anakin hasn't slept in a week. 'She's dying, Master. I can feel it.' The Council wants you both on Coruscant guarding the Chancellor.",
        options: [
          { label: 'Take him to Tatooine, against orders', effects: { flags_add: ['saved_shmi_attempt'], alignment: 5 }, log: "You broke Council orders and took Anakin to Tatooine to search for his mother." },
          { label: "Tell him to trust the Council", effects: { alignment: -5 }, log: "You told Anakin to let go and trust the Council. Something in him closed off from you a little that day." },
        ] },
      { year: -19, title: 'The Mustafar Choice', requiresFlag: 'master_of_anakin',
        text: "Word reaches you: Anakin has gone to Mustafar, and the Temple younglings are dead. Everything the Order feared is coming true.",
        options: [
          { label: 'Go after him yourself', effects: { flags_add: ['confronted_anakin_mustafar'], alignment: 10 }, log: "You went to Mustafar to face your fallen Padawan yourself, for better or worse." },
          { label: 'Go into hiding instead', effects: { flags_add: ['jedi_in_hiding'], alignment: -5 }, log: "You chose survival over confrontation, and disappeared into the Outer Rim like so many other Jedi." },
        ] },
    ],
  },
  ARC_MASTER_LUKE: {
    label: 'Train Luke Skywalker',
    triggerFlags: ['jedi_knight', 'jedi_master'],
    triggerYear: 0,
    beats: [
      { year: 0, title: 'A New Hope',
        text: "A young man from Tatooine has stumbled into your life carrying a message from Princess Leia and a father's old lightsaber. He wants to learn the ways of the Force.",
        options: [
          { label: 'Take him as your student', effects: { flags_add: ['master_of_luke'], alignment: 8 }, log: "You agreed to train Luke Skywalker, the last hope of a nearly-extinguished Order." },
          { label: 'Send him away for his own safety', effects: {}, log: "You sent Luke away, unwilling to risk another apprentice to the dark side." },
        ] },
      { year: 3, title: 'The Cave on Dagobah', requiresFlag: 'master_of_luke',
        text: "Luke wants to leave his training early — he's sensed his friends are in terrible danger at Cloud City.",
        options: [
          { label: 'Forbid him to go', effects: { alignment: 5 }, log: "You warned Luke against leaving, but some choices aren't yours to make for him." },
          { label: 'Let him choose his own path', effects: { flags_add: ['let_luke_go'] }, log: "You let Luke go to Bespin, trusting him to find his own way through the test ahead." },
        ] },
      { year: 4, title: 'The Second Death Star', requiresFlag: 'master_of_luke',
        text: "The Rebellion is preparing to strike the second Death Star above Endor. Luke intends to confront Vader and the Emperor alone.",
        options: [
          { label: 'Go with him', effects: { flags_add: ['present_at_endor'], alignment: 10 }, log: "You stood with Luke in the Emperor's throne room as the battle raged above Endor." },
          { label: 'Trust him to face it alone', effects: { alignment: 5 }, log: "You let Luke face his father alone, believing — rightly, it turned out — that this was his alone to carry." },
        ] },
    ],
  },
  ARC_MASTER_BEN_SOLO: {
    label: 'Train Ben Solo',
    triggerFlags: ['jedi_knight', 'jedi_master'],
    triggerYear: 15,
    beats: [
      { year: 15, title: "Han and Leia's Son",
        text: "Han and Leia Organa-Solo bring you their son. He's powerful — frighteningly so — and something ancient and hungry already seems to be whispering to him in the dark.",
        options: [
          { label: 'Take him as your student', effects: { flags_add: ['master_of_ben'], alignment: 5 }, log: "You agreed to train young Ben Solo, aware of the shadow already stretching toward him." },
          { label: 'Warn his parents and decline', effects: {}, log: "You told Han and Leia their son needed a different teacher, and stepped back." },
        ] },
      { year: 27, title: 'The Whispering', requiresFlag: 'master_of_ben',
        text: "You've started sensing something reaching for Ben in his sleep — a presence from beyond, patient and old.",
        options: [
          { label: 'Confront Ben directly', effects: { flags_add: ['confronted_ben'], alignment: 5 }, log: "You told Ben what you sensed. He didn't take it well." },
          { label: 'Watch and wait', effects: { alignment: -5 }, log: "You decided to watch quietly rather than alarm him. In hindsight, you're not sure that was wise." },
        ] },
      { year: 28, title: 'The Night of the Burning', requiresFlag: 'master_of_ben',
        text: "You stand over Ben's hut in the dark, lightsaber in hand, certain for one terrible instant that he's already lost. The moment stretches. Everything depends on what you do next.",
        options: [
          { label: 'Lower the blade and reach for him', successChance: 0.5, effects: { flags_add: ['saved_ben_solo'], alignment: 15 }, failEffects: { flags_add: ['temple_destroyed'], alignment: -10 }, log: "You lowered your blade and reached for Ben instead — and just this once, it was enough.", failLog: "You hesitated a moment too long. By the time you lowered the blade, the temple was already burning behind you." },
          { label: 'Strike first', effects: { flags_add: ['killed_ben_solo'], alignment: -30 }, log: "You struck. Whatever the galaxy might have been with Ben Solo in it ends here, by your hand." },
        ] },
    ],
  },
  ARC_VADER_APPRENTICE: {
    label: "Vader's Secret Apprentice",
    triggerFlags: ['inquisitor_trainee', 'sith_acolyte'],
    triggerYear: -14,
    beats: [
      { year: -14, title: "A Different Kind of Offer",
        text: "Darth Vader has taken a personal interest in your training — unusual, for a mere Inquisitor. 'The Emperor need not know of this arrangement,' he says.",
        options: [
          { label: "Accept Vader's secret tutelage", effects: { flags_add: ['vader_apprentice'], alignment: -15 }, log: "You became Darth Vader's secret apprentice, hidden from the Emperor himself." },
          { label: 'Report the offer to Palpatine', effects: { flags_add: ['loyal_to_emperor'], alignment: -5 }, log: "You reported Vader's offer directly to the Emperor. Vader's expression, beneath the mask, was unreadable." },
        ] },
      { year: -5, title: 'The Hunt for Ahsoka Tano', requiresFlag: 'vader_apprentice',
        text: "Vader sends you after a target of his own choosing: a former Jedi who abandoned the Order before the Purge. Killing her would prove your loyalty beyond question.",
        options: [
          { label: 'Carry out the hunt', effects: { flags_add: ['hunted_ahsoka'], alignment: -20 }, log: "You hunted Ahsoka Tano across the Outer Rim on Vader's orders, whatever doubts it raised in you." },
          { label: 'Let her slip away', effects: { flags_add: ['spared_ahsoka'], alignment: 10 }, log: "You let her escape, and told Vader the trail went cold. You're not entirely sure why." },
        ] },
      { year: 0, title: "The Emperor's Discovery", requiresFlag: 'vader_apprentice',
        text: "Somehow, Palpatine has learned of Vader's secret apprentice. Both of you are summoned to his private chambers.",
        options: [
          { label: 'Stand with Vader', successChance: 0.5, effects: { flags_add: ['survived_emperor_wrath'], alignment: -10 }, failEffects: {}, log: "The Emperor let it pass — for now — deciding two dangerous Sith were more useful than one dead apprentice.", failLog: "The Emperor's lightning found you before Vader could so much as raise a hand." , fatal: true},
        ] },
    ],
  },
};

/* ---------------- CONDENSED STORY ARCS ---------------- */
const SLAVE_ARC = {
  label: 'A Life in Chains',
  beats: [
    { ageOffset: 6, title: 'Put to Work',
      text: "You're old enough now to be useful. Your owner decides what that means: the pit, the pod-track, the mines, or running errands nobody else wants.",
      options: [
        { label: 'Work the pod-mechanic bay', effects: { flags_add: ['pod_mechanic'], smarts: 4 }, log: "You learned to keep engines running, hands perpetually black with grease." },
        { label: 'Work as a runner and courier', effects: { flags_add: ['slave_courier'], looks: 2, smarts: 2 }, log: "You learned every back alley in the district, carrying messages and packages nobody wanted traced." },
      ] },
    { ageOffset: 14, title: 'The Chip',
      text: "You've found where your owner keeps the detonator override for slave chips like yours — a single, terrifying chance.",
      options: [
        { label: 'Attempt to disable your chip', successChance: 0.55, effects: { flags_add: ['chip_disabled'], happiness: 15 }, failEffects: { health: -15 }, log: "With a friend's help, you disabled the chip. For the first time, running doesn't mean dying.", failLog: "The attempt failed and the chip very nearly killed you. You'll have to be more careful." },
        { label: 'Stay cautious and wait for a better chance', effects: {}, log: "You decided the risk wasn't worth it, not yet." },
      ] },
    { ageOffset: 20, title: 'Freedom, One Way or Another',
      text: "An opportunity for freedom has finally appeared — however it comes, it won't come again.",
      options: [
        { label: 'Bet everything on a podrace', successChance: 0.4, effects: { flags_add: ['freed_podrace'], happiness: 20, wealth: 2000 }, failEffects: { happiness: -10 }, log: "You won your freedom in a podrace that will be talked about for years.", failLog: "You lost the race, and with it, your best shot at freedom for now." },
        { label: 'Run, chip or no chip', successChance: 0.5, effects: { flags_add: ['freed_runaway'], happiness: 15 }, failEffects: { flags_add: ['recaptured'], happiness: -15 }, log: "You ran, and against the odds, you made it.", failLog: "You were caught before you got off-world. Things are worse now." },
      ] },
  ],
};

const MANDO_ARC = {
  label: 'This Is the Way',
  beats: [
    { ageOffset: 13, title: "Verd'goten",
      text: "Your clan holds your Verd'goten — the trial that proves you're ready to be counted an adult, and a warrior.",
      options: [
        { label: 'Face the trial head-on', successChance: 0.7, effects: { flags_add: ['verd_goten_passed'], happiness: 10, health: 5 }, failEffects: { health: -10 }, log: "You passed your Verd'goten. The clan sees you differently now.", failLog: "The trial nearly broke you, but the clan still claims you as one of their own." },
      ] },
    { ageOffset: 20, title: 'The Civil War',
      text: "Death Watch has moved against the ruling government of Mandalore. Every warrior has to choose a side, or be considered one anyway.",
      options: [
        { label: 'Fight for Death Watch', effects: { flags_add: ['death_watch'], alignment: -10 }, log: "You joined Death Watch's cause, believing the old ways of war were the only honest ones left." },
        { label: 'Defend the ruling government', effects: { flags_add: ['loyalist_mando'], alignment: 10 }, log: "You stood against Death Watch, believing peace was worth defending even at a cost." },
        { label: 'Stay neutral and protect your clan', effects: { flags_add: ['neutral_mando'] }, log: "You kept your clan out of the war entirely, whatever that cost your standing among other Mandalorians." },
      ] },
  ],
};

const CLONE_ARC = {
  label: "A Soldier's Life",
  beats: [
    { ageOffset: 10, title: 'Assignment',
      text: "Training on Kamino is complete. The Kaminoans assign you to a legion and ship you to the front within the week.",
      options: [
        { label: 'Front-line trooper', effects: { flags_add: ['legion_trooper'], health: 4 }, log: "You shipped out to the front lines as a rank-and-file clone trooper." },
        { label: 'ARC trooper track', effects: { flags_add: ['arc_trooper'], smarts: 4, health: 4 }, log: "You were selected for advanced recon commando training — independent thought was, unusually, encouraged." },
      ] },
    { ageOffset: 16, title: 'The Chip Conspiracy',
      text: "A trooper named Fives is telling anyone who'll listen that there's a biochip in every clone's head meant to make them turn on the Jedi. Command wants him quietly silenced.",
      options: [
        { label: 'Believe him and investigate quietly', effects: { flags_add: ['believed_fives'] }, log: "You looked into Fives's claims quietly. What you found didn't sit right." },
        { label: 'Dismiss it as combat fatigue', effects: {}, log: "You dismissed the chip conspiracy as battle fatigue talking, and tried not to think about it again." },
      ] },
    { ageOffset: 17, title: 'Order 66',
      text: "The order comes through your comm exactly like every other tactical order — except this one is to execute your own Jedi general.",
      options: [
        { label: '(Chip intact) Carry out the order', requiresNotFlag: 'chip_removed', effects: { flags_add: ['executed_order_66'], alignment: -10 }, log: "The chip did its work. You fired on your own general without a moment's hesitation you can remember." },
        { label: '(Chip removed) Refuse and warn your general', requiresFlag: 'chip_removed', effects: { flags_add: ['refused_order_66'], alignment: 15 }, log: "With your chip removed, you refused the order and warned your general instead — a death sentence if anyone found out." },
      ] },
  ],
};
